[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "8DXC6GMDneGhysZHX8uVZDXPuJBUGXHcJcymYov1ePhN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/abhi3700/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world'"